# Generated by Django 3.1.4 on 2021-11-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videopost_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopost',
            options={'ordering': ['-published'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
