# Generated by Django 3.1.4 on 2021-11-28 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20211124_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.videopost', verbose_name='коментируемое видео'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(upload_to='video/items/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='видео'),
        ),
    ]
