# Generated by Django 3.1.4 on 2021-12-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20211212_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='author',
            field=models.ForeignKey(default='dima', on_delete=django.db.models.deletion.CASCADE, to='video.author', verbose_name='автор'),
        ),
    ]
