# Generated by Django 3.1.4 on 2021-12-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20211220_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.author', verbose_name='автор'),
        ),
    ]
